name: Docker Build
on:
  workflow_dispatch:
    inputs:
      push_build:
        description: 'Should the build-push-action push to the registry?'
        required: true
        default: false
        type: boolean
  push:
    branches:
      - main
    paths:
      - Dockerfile

jobs:
  docker-build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-24.04, ubuntu-24.04-arm]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
          sparse-checkout-cone-mode: false
      - name: Parse Caddy version
        id: version
        run: echo "version=$(grep -Eo 'caddy:[0-9]+\.[0-9]+\.[0-9]+$' Dockerfile | cut -d ':' -f2)" | tee -a $GITHUB_OUTPUT
      - name: Generate Docker metadata with Caddy version
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/emarshal/caddy-custom
          tags: |
            type=semver,pattern={{version}},value=v${{ steps.version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ steps.version.outputs.version }}
            type=semver,pattern={{major}},value=v${{ steps.version.outputs.version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          annotations: ${{ steps.meta.outputs.annotations }}
          context: .
          no-cache: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ (matrix.os == 'ubuntu-24.04' && 'linux/amd64') || (matrix.os == 'ubuntu-24.04-arm' && 'linux/arm64') }}
          provenance: mode=min
          push: ${{ github.event_name == 'push' && 'true' || inputs.push_build == true }}
          tags: ${{ steps.meta.outputs.tags }}
